language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: info@collectorbank.se
  api_key:
    secure: 0472f921-e57a-4529-844d-dd50cf95fe03
  on:
    repo: collector-bank/collector-portal-framework
    branch: master
  skip_cleanup: true
